import 'package:flutter_test/flutter_test.dart';
import 'package:nutro_ai/models/meal_model.dart';
import 'package:nutro_ai/utils/chat_timeline_builder.dart';

void main() {
  test('interleaves a recovered card at its original conversation time', () {
    final userTime = DateTime(2026, 7, 8, 10);
    final cardTime = userTime.add(const Duration(seconds: 1));
    final nextUserTime = userTime.add(const Duration(minutes: 2));
    final meal = Meal(
      id: 'meal-1',
      type: MealType.lunch,
      foods: const [],
      dateTime: DateTime(2026, 7, 8),
      messageId: 'msg-${cardTime.microsecondsSinceEpoch}',
    );

    final timeline = ChatTimelineBuilder.build(
      messages: [
        {'isUser': true, 'message': 'arroz', 'timestamp': userTime},
        {
          'isUser': true,
          'message': 'quanto falta?',
          'timestamp': nextUserTime,
        },
      ],
      unrepresentedMeals: [meal],
    );

    expect(timeline, hasLength(3));
    expect(timeline[0].messageIndex, 0);
    expect(timeline[1].isMessage, isFalse);
    expect(timeline[1].meals.single.id, 'meal-1');
    expect(timeline[2].messageIndex, 1);
  });

  test('groups multiple meal cards generated by the same assistant message',
      () {
    final cardTime = DateTime(2026, 7, 8, 12);
    final baseId = 'msg-${cardTime.microsecondsSinceEpoch}';

    final timeline = ChatTimelineBuilder.build(
      messages: const <Map<String, dynamic>>[],
      unrepresentedMeals: [
        Meal(
          id: 'meal-1',
          type: MealType.lunch,
          foods: const [],
          dateTime: cardTime,
          messageId: '$baseId#meal-0',
        ),
        Meal(
          id: 'meal-2',
          type: MealType.snack,
          foods: const [],
          dateTime: cardTime,
          messageId: '$baseId#meal-1',
        ),
      ],
    );

    expect(timeline, hasLength(1));
    expect(timeline.single.meals.map((meal) => meal.id), ['meal-1', 'meal-2']);
  });

  test('hides the previous meal while its message is being regenerated', () {
    final cardTime = DateTime(2026, 7, 8, 12);
    final messageId = 'msg-${cardTime.microsecondsSinceEpoch}';

    final timeline = ChatTimelineBuilder.build(
      messages: [
        {
          'isUser': true,
          'id': 'usr-1',
          'message': 'pao',
          'timestamp': cardTime.subtract(const Duration(seconds: 1)),
        },
        {
          'isUser': false,
          'id': messageId,
          'timestamp': cardTime,
          'notifier': Object(),
          'replaceExistingMeals': true,
        },
      ],
      unrepresentedMeals: [
        Meal(
          id: 'old-meal',
          type: MealType.breakfast,
          foods: const [],
          dateTime: cardTime,
          messageId: messageId,
        ),
      ],
    );

    expect(timeline, hasLength(2));
    expect(timeline.every((item) => item.isMessage), isTrue);
  });

  test('shows assistant actions only after loading finishes', () {
    final messages = <Map<String, dynamic>>[
      {
        'isUser': true,
        'message': 'pao',
        'timestamp': DateTime(2026, 7, 8, 12),
      },
      {
        'isUser': false,
        'message': 'resposta',
        'timestamp': DateTime(2026, 7, 8, 12, 0, 1),
      },
    ];

    expect(
      ChatTimelineBuilder.shouldShowAssistantActions(
        messages: messages,
        isLoading: true,
      ),
      isFalse,
    );
    expect(
      ChatTimelineBuilder.shouldShowAssistantActions(
        messages: messages,
        isLoading: false,
      ),
      isTrue,
    );
  });
}
