import 'package:flutter_test/flutter_test.dart';
import 'package:nutro_ai/models/meal_model.dart';
import 'package:nutro_ai/utils/chat_timeline_builder.dart';

void main() {
  test('interleaves a recovered card at its original conversation time', () {
    final userTime = DateTime(2026, 7, 8, 10);
    final cardTime = userTime.add(const Duration(seconds: 1));
    final nextUserTime = userTime.add(const Duration(minutes: 2));
    final meal = Meal(
      id: 'meal-1',
      type: MealType.lunch,
      foods: const [],
      dateTime: DateTime(2026, 7, 8),
      messageId: 'msg-${cardTime.microsecondsSinceEpoch}',
    );

    final timeline = ChatTimelineBuilder.build(
      messages: [
        {'isUser': true, 'message': 'arroz', 'timestamp': userTime},
        {
          'isUser': true,
          'message': 'quanto falta?',
          'timestamp': nextUserTime,
        },
      ],
      unrepresentedMeals: [meal],
    );

    expect(timeline, hasLength(3));
    expect(timeline[0].messageIndex, 0);
    expect(timeline[1].isMessage, isFalse);
    expect(timeline[1].meals.single.id, 'meal-1');
    expect(timeline[2].messageIndex, 1);
  });

  test('groups multiple meal cards generated by the same assistant message',
      () {
    final cardTime = DateTime(2026, 7, 8, 12);
    final baseId = 'msg-${cardTime.microsecondsSinceEpoch}';

    final timeline = ChatTimelineBuilder.build(
      messages: const <Map<String, dynamic>>[],
      unrepresentedMeals: [
        Meal(
          id: 'meal-1',
          type: MealType.lunch,
          foods: const [],
          dateTime: cardTime,
          messageId: '$baseId#meal-0',
        ),
        Meal(
          id: 'meal-2',
          type: MealType.snack,
          foods: const [],
          dateTime: cardTime,
          messageId: '$baseId#meal-1',
        ),
      ],
    );

    expect(timeline, hasLength(1));
    expect(timeline.single.meals.map((meal) => meal.id), ['meal-1', 'meal-2']);
  });
}
