name: nutro_ai
description: "Nutro AI - Your intelligent nutrition assistant"
publish_to: 'none'
version: 1.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.4.8
  supabase_flutter: ^2.6.0
  image_picker: ^1.0.7
  video_player: ^2.9.2
  file_picker: ^8.1.2
  path_provider: ^2.1.4
  google_fonts: ^4.0.3
  fl_chart: ^0.70.2
  provider: ^6.1.4
  http: ^1.1.0
  uuid: ^4.3.3
  intl: ^0.20.2
  timeago: ^3.5.0
  youtube_explode_dart: ^2.3.10
  youtube_player_flutter: ^9.1.1
  google_sign_in: ^6.1.5
  flutter_secure_storage: ^9.0.0
  in_app_purchase: ^3.2.1
  flutter_tts: ^3.8.5
  google_mobile_ads: ^6.0.0
  
  # Substituir google_ml_kit completo por plugins específicos para reduzir tamanho
  # google_ml_kit: ^0.20.0
  google_mlkit_text_recognition: ^0.15.0
  
  permission_handler: ^11.4.0
  speech_to_text: ^7.0.0
  flutter_math_fork: ^0.7.2
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  flutter_inappwebview: ^6.0.0
  camera: ^0.10.5+5
  image: ^4.1.6
  flutter_staggered_animations: ^1.1.1
  in_app_update: ^4.2.2
  font_awesome_flutter: ^10.8.0
  package_info_plus: ^8.3.0
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#f6fae9"
  adaptive_icon_foreground: "assets/images/logo_foreground.png"
  
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/images/
    - assets/link_test.txt