String _normalizeFoodName(String value) {
  const replacements = {
    'á': 'a',
    'à': 'a',
    'ã': 'a',
    'â': 'a',
    'ä': 'a',
    'é': 'e',
    'è': 'e',
    'ê': 'e',
    'ë': 'e',
    'í': 'i',
    'ì': 'i',
    'î': 'i',
    'ï': 'i',
    'ó': 'o',
    'ò': 'o',
    'õ': 'o',
    'ô': 'o',
    'ö': 'o',
    'ú': 'u',
    'ù': 'u',
    'û': 'u',
    'ü': 'u',
    'ç': 'c',
  };

  var normalized = value.toLowerCase();
  replacements.forEach((from, to) {
    normalized = normalized.replaceAll(from, to);
  });

  return normalized
      .replaceAll(RegExp(r'[^a-z0-9]+'), ' ')
      .replaceAll(RegExp(r'\s+'), ' ')
      .trim();
}

int _foodTermScore(String normalizedName, String term) {
  final normalizedTerm = _normalizeFoodName(term);
  if (normalizedTerm.isEmpty) return -1;

  final hasMatch = RegExp(
    '(^| )${RegExp.escape(normalizedTerm)}( |s(?= |\$)|es(?= |\$)|\$)',
  ).hasMatch(normalizedName);

  return hasMatch ? normalizedTerm.length : -1;
}

String resolveFoodEmoji(String name, {String? preferred}) {
  if (preferred != null &&
      preferred.trim().isNotEmpty &&
      preferred.trim() != '🍽️') {
    return preferred.trim();
  }

  final normalized = _normalizeFoodName(name);
  const emojiMatchers = <MapEntry<List<String>, String>>[
    MapEntry([
      'ovo cozido',
      'ovo de galinha',
      'ovo inteiro',
      'boiled egg',
    ], '🥚'),
    MapEntry([
      'ovo',
      'ovos',
      'omelete',
      'omeleta',
      'mexido',
      'mexidos',
      'clara',
      'gema',
      'egg',
      'eggs',
      'omelet',
    ], '🍳'),
    MapEntry([
      'peito de frango',
      'frango grelhado',
      'frango desfiado',
      'frango assado',
      'frango',
      'sobrecoxa',
      'coxa',
      'asa de frango',
      'galinha',
      'chicken',
      'grilled chicken',
      'shredded chicken',
    ], '🍗'),
    MapEntry([
      'carne moida',
      'carne moída',
      'carne bovina',
      'contrafile',
      'contrafilé',
      'carne',
      'bife',
      'bife acebolado',
      'alcatra',
      'patinho',
      'picanha',
      'file mignon',
      'filé mignon',
      'maminha',
      'acém',
      'acem',
      'beef',
      'steak',
    ], '🥩'),
    MapEntry(['cordeiro', 'costela', 'costelinha', 'ribs', 'lamb'], '🍖'),
    MapEntry(['hamburguer', 'hamburger', 'burger'], '🍔'),
    MapEntry([
      'hot dog',
      'cachorro quente',
      'salsicha',
      'sausage',
    ], '🌭'),
    MapEntry(['bacon', 'presunto', 'panceta', 'pork belly'], '🥓'),
    MapEntry([
      'porco',
      'suino',
      'suíno',
      'lombo',
      'pernil',
      'pork',
      'pork loin',
    ], '🥩'),
    MapEntry(['peito de peru', 'peru', 'turkey'], '🍗'),
    MapEntry([
      'salmao',
      'salmão',
      'atum',
      'tilapia',
      'tilápia',
      'sardinha',
      'bacalhau',
      'truta',
      'pescada',
      'file de peixe',
      'filé de peixe',
      'peixe',
      'fish',
      'salmon',
      'tuna',
      'cod',
    ], '🐟'),
    MapEntry([
      'camarao',
      'camarão',
      'lula',
      'polvo',
      'marisco',
      'shrimp',
      'seafood',
    ], '🍤'),
    MapEntry(['sushi', 'sashimi', 'temaki', 'poke'], '🍣'),
    MapEntry([
      'arroz integral',
      'arroz branco',
      'arroz parboilizado',
      'arroz',
      'risoto',
      'rice',
      'risotto',
    ], '🍚'),
    MapEntry([
      'feijao',
      'feijão',
      'lentilha',
      'grao de bico',
      'grão de bico',
      'ervilha seca',
      'feijao carioca',
      'feijão carioca',
      'feijao preto',
      'feijão preto',
      'feijao fradinho',
      'feijão fradinho',
      'beans',
      'lentils',
      'chickpea',
    ], '🫘'),
    MapEntry(['ervilha', 'edamame', 'pea', 'peas'], '🫛'),
    MapEntry([
      'quinoa',
      'cevada',
      'trigo',
      'farro',
      'barley',
      'bulgur',
      'farelo',
      'farelo de aveia',
      'farinha de mandioca',
      'farinha',
    ], '🌾'),
    MapEntry([
      'aveia',
      'aveia em flocos',
      'granola',
      'cereal',
      'mingau',
      'muesli',
      'oats',
      'oatmeal',
    ], '🥣'),
    MapEntry([
      'macarrao',
      'macarrão',
      'espaguete',
      'lasanha',
      'nhoque',
      'ravioli',
      'massa',
      'penne',
      'fusilli',
      'pasta',
      'spaghetti',
    ], '🍝'),
    MapEntry(['lamen', 'ramen', 'noodle', 'yakisoba'], '🍜'),
    MapEntry(['pizza'], '🍕'),
    MapEntry([
      'pao',
      'pão',
      'pao frances',
      'pão francês',
      'pao integral',
      'pão integral',
      'pao de forma',
      'pão de forma',
      'torrada',
      'croissant',
      'bagel',
      'sanduiche',
      'sanduíche',
      'toast',
      'bread',
      'sandwich',
    ], '🥖'),
    MapEntry(['pao de queijo', 'pão de queijo', 'cheese bread'], '🧀'),
    MapEntry(['biscoito de arroz', 'rice cracker'], '🍘'),
    MapEntry(['pastel', 'coxinha', 'empada', 'dumpling'], '🥟'),
    MapEntry([
      'farinha de tapioca',
      'tapioca',
      'crepioca',
      'wrap',
      'tortilla',
      'pita',
      'flatbread',
    ], '🫓'),
    MapEntry(['panqueca', 'pancake'], '🥞'),
    MapEntry(['waffle'], '🧇'),
    MapEntry([
      'queijo',
      'mussarela',
      'muçarela',
      'parmesao',
      'parmesão',
      'minas',
      'ricota',
      'cottage',
      'requeijao',
      'requeijão',
      'cream cheese',
      'cheese',
    ], '🧀'),
    MapEntry(['manteiga', 'butter', 'ghee'], '🧈'),
    MapEntry(['leite', 'milk'], '🥛'),
    MapEntry([
      'iogurte grego',
      'iogurte natural',
      'iogurte',
      'coalhada',
      'kefir',
      'yogurt',
      'yoghurt',
    ], '🥣'),
    MapEntry([
      'whey protein',
      'whey',
      'shake',
      'smoothie',
      'vitamina',
      'protein shake',
    ], '🥤'),
    MapEntry([
      'cafe com leite',
      'café com leite',
      'cafe',
      'café',
      'capuccino',
      'espresso',
      'coffee'
    ], '☕'),
    MapEntry(['cha', 'chá', 'tea'], '🫖'),
    MapEntry([
      'suco de laranja',
      'suco de uva',
      'suco de limao',
      'suco de limão',
      'suco de maca',
      'suco de maçã',
      'suco',
      'juice',
    ], '🧃'),
    MapEntry(['agua de coco', 'água de coco', 'coconut water'], '🥥'),
    MapEntry(['agua', 'água', 'water'], '💧'),
    MapEntry(['refrigerante', 'soda'], '🥤'),
    MapEntry(['vinho', 'wine'], '🍷'),
    MapEntry(['cerveja', 'beer'], '🍺'),
    MapEntry(
        ['banana', 'banana prata', 'banana nanica', 'banana da terra'], '🍌'),
    MapEntry(['maca', 'maçã', 'apple'], '🍎'),
    MapEntry(['pera', 'pear'], '🍐'),
    MapEntry(['laranja', 'tangerina', 'mexerica', 'orange'], '🍊'),
    MapEntry(['limao', 'limão', 'lemon', 'lime'], '🍋'),
    MapEntry(
        ['uva', 'uva passa', 'passas', 'grape', 'raisin', 'raisins'], '🍇'),
    MapEntry(['morango', 'strawberry'], '🍓'),
    MapEntry(['mirtilo', 'blueberry', 'blueberries'], '🫐'),
    MapEntry(['cereja', 'cherry'], '🍒'),
    MapEntry(['pessego', 'pêssego', 'peach'], '🍑'),
    MapEntry(['melancia', 'watermelon'], '🍉'),
    MapEntry(['abacaxi', 'pineapple'], '🍍'),
    MapEntry(['mamao', 'mamão', 'manga', 'papaya', 'mango'], '🥭'),
    MapEntry(['abacate', 'avocado'], '🥑'),
    MapEntry(['goiaba', 'guava'], '🍈'),
    MapEntry(['melao', 'melão', 'melon'], '🍈'),
    MapEntry(['kiwi'], '🥝'),
    MapEntry(['coco', 'coconut'], '🥥'),
    MapEntry(['acai', 'açaí'], '🫐'),
    MapEntry(['salada de frutas', 'fruit salad'], '🍓'),
    MapEntry(['tomate', 'tomate cereja', 'tomato'], '🍅'),
    MapEntry(['brocolis', 'brócolis', 'broccoli'], '🥦'),
    MapEntry(['couve flor', 'couve-flor', 'cauliflower'], '🥦'),
    MapEntry(['alface', 'lettuce'], '🥬'),
    MapEntry([
      'couve',
      'espinafre',
      'rucula',
      'rúcula',
      'acelga',
      'repolho',
      'agrião',
      'agriao',
      'spinach',
      'cabbage',
    ], '🥬'),
    MapEntry(['pepino', 'cucumber'], '🥒'),
    MapEntry(['cenoura', 'carrot'], '🥕'),
    MapEntry(['milho', 'cuscuz', 'polenta', 'corn'], '🌽'),
    MapEntry(['batata doce', 'sweet potato'], '🍠'),
    MapEntry([
      'batata',
      'mandioca',
      'aipim',
      'macaxeira',
      'inhame',
      'potato',
      'cassava'
    ], '🥔'),
    MapEntry(['abobora', 'abóbora', 'moranga', 'pumpkin'], '🎃'),
    MapEntry(['beterraba', 'beetroot', 'beet'], '🥗'),
    MapEntry(['vagem', 'green bean', 'green beans'], '🫛'),
    MapEntry(['palmito', 'heart of palm'], '🥬'),
    MapEntry(['quiabo', 'okra'], '🫑'),
    MapEntry(['pimentao', 'pimentão', 'bell pepper'], '🫑'),
    MapEntry(['cebola', 'onion'], '🧅'),
    MapEntry(['alho', 'garlic'], '🧄'),
    MapEntry(['cogumelo', 'mushroom'], '🍄'),
    MapEntry(['berinjela', 'eggplant'], '🍆'),
    MapEntry(['abobrinha', 'zucchini'], '🥒'),
    MapEntry(['pimenta', 'pepper', 'chili'], '🌶️'),
    MapEntry(['salada', 'salad', 'legumes', 'vegetais', 'vegetables'], '🥗'),
    MapEntry([
      'sopa de legumes',
      'sopa de frango',
      'canja',
      'sopa',
      'caldo',
      'ensopado',
      'soup',
      'stew',
    ], '🍲'),
    MapEntry(['curry', 'strogonoff', 'stroganoff'], '🍛'),
    MapEntry([
      'oleo de soja',
      'óleo de soja',
      'oleo vegetal',
      'óleo vegetal',
      'oleo',
      'óleo',
      'vegetable oil',
      'soybean oil',
      'oil',
    ], '🫒'),
    MapEntry([
      'tofu',
      'tempeh',
      'proteina de soja',
      'proteína de soja',
      'soja',
      'soy'
    ], '🫘'),
    MapEntry(['homus', 'hummus', 'falafel'], '🧆'),
    MapEntry(['azeite', 'azeitona', 'oliva', 'olive oil', 'olive'], '🫒'),
    MapEntry([
      'pasta de amendoim',
      'castanha',
      'castanhas',
      'amendoim',
      'noz',
      'nozes',
      'amendoas',
      'amêndoas',
      'pistache',
      'macadamia',
      'avelã',
      'avela',
      'nuts',
      'peanut',
      'almond',
      'peanut butter',
    ], '🥜'),
    MapEntry([
      'chia',
      'linhaca',
      'linhaça',
      'gergelim',
      'semente',
      'sementes',
      'seed',
      'seeds',
    ], '🌱'),
    MapEntry(['mel', 'geleia', 'honey', 'jam'], '🍯'),
    MapEntry([
      'bolo de cenoura',
      'bolo de chocolate',
      'bolo',
      'torta',
      'cupcake',
      'cake',
      'pie',
    ], '🍰'),
    MapEntry(['biscoito', 'bolacha', 'cookie'], '🍪'),
    MapEntry(['chocolate', 'cacau', 'brigadeiro', 'cocoa'], '🍫'),
    MapEntry(['sorvete', 'gelato', 'ice cream'], '🍨'),
    MapEntry(['pudim', 'flan', 'pudding'], '🍮'),
    MapEntry(['doce', 'bala', 'candy'], '🍬'),
  ];

  String? bestEmoji;
  var bestScore = -1;

  for (final entry in emojiMatchers) {
    for (final term in entry.key) {
      final score = _foodTermScore(normalized, term);
      if (score > bestScore) {
        bestScore = score;
        bestEmoji = entry.value;
      }
    }
  }

  return bestEmoji ?? '🍽️';
}
